DBPassword: 123
DBLogin: 123
DBImplement: "mongodb"
host: "mongodb://localhost"
port: ":27017"
database: "dev"
collection: "trainers"
log_collection: "log"
path: "C:/Users/ryabi/Downloads/biocad_file"
destination_path: "C:/Users/ryabi/Downloads/biocad_dest"
frequency_of_dir_checks: 5 #sec
web_server_port: ":8000"



pageSize: 10