headerFont: ArialUnicode
headerSize: 16.0
tableFont: ArialUnicode
tableSize: 8.0
tableHeaderSize: 10.0
borderType: "1"
fileName: "table"

font_path: "src/pdfGenerator/font/Arial Unicode MS.ttf"
report_path: "C:/Users/ryabi/Downloads/biocad_dest"